### PR TITLE
Movable Constraint Modifications

### PR DESCRIPTION
**Pull request by dgwaldo**
Allows a movable to be constrained with a bumper directive.  When the
movable hits the bumper div it should be constrained.  

Also, it seems that this changes highlights an existing bug where when the cursor hits the edge of the window the movable gets reset to top=0 left=0.  You can see the behavior in the current branch if you try and drag the movable out of bounds.

### CODE REVIEW

**Comment by spali** [comment]
Thanks for working on this.

I see one problem, it does not support multiple movable containers to have different bumper's.

I see two solutions:
- implement it like the `MovableHandleDirective` to name optionally the bumper it should be constrained to.
```
<div movableBumper="bumper2">
    <div movable [movableEnabled]="toggle" bumper="bumper2">
        <div><b>Simple movable</b></div>
        The complete element can be used for moving.<br />
        <button (click)="toggle = !toggle">toggle enabled state</button>
      </div>
</div>
```
What I don't like in this solution is that it requires an additional directive and an input property on `MovableDirective` for referencing the bumper.

- or what i prefer over the first solution, instead of the additional directive `MovableBumperDirective`, the bumper could be referenced directly by i.e. the id or even a selector expression in the 'MoveableDirective` as a input property (this because the bumper doesn't need any code by itself).
It also would allow to simple change the property on runtime to change the element reference.
```
<div id="bumper2">
    <div movable [movableEnabled]="toggle" constrainedId="bumper2">
        <div><b>Simple movable</b></div>
        The complete element can be used for moving.<br />
        <button (click)="toggle = !toggle">toggle enabled state</button>
      </div>
</div>
```
What do you think?
In the meantime I try to fix #6

**Comment by spali** [comment]
Thought about the selector possibility... I think this would make it to complex and in-transparent.

So my design suggestion would be:
- `@Input()` property named `movableContainment` on `MovableDirective`  which refers the id of the containment element (I would use the `id` to prevent by design to have multiple containment's. I don't see currently any use case for having more than one containment. 
- then walk up the parent's until the id match to find the containment element to check position agains.
- if possible please do not use `getBoundingClientRect()`. I had a lot of trouble in some situations with strange side effects using this method (I think this method does not return in all situations the expected values).
- if possible create a new example for this, the `Movable 1` example doesn't create a good view on this feature at first sight. 

I have some spare minutes currently and could do it by my self, but I don't wan't to throw away your work and credits for the pull request. But let me know if you want to rework your pull request or if I should give it a try ;)

**Comment by dgwaldo** [comment]
I'm in agreement that one containing element will probably handle most use cases.  Our current use case is we just want the windows to not float up out of the app.  

I'm not sure how to get the correct positions without using getBoundingClientRect().  If you don't use that function you're left with manually calculating the correct positions.  

Feel free to implement it yourself if I'm holding things up.  I more or less just wanted to prove out the concept :)  I probably won't have much time again till the weekend.

**Comment by dgwaldo** [comment]
Also, just noticed that this has issues where it sticks if any side of the movable box ends up touching the constraint.  If you hit the sides you should still be able to move up and down, if you hit top or bottom you should still be able to move left or right... :)  I think this was useful for proving out the concept but this should probably be taken into consideration as well.

**Comment by spali** [comment]
just want to let you know, I'm working on it, but I realized, there are some other strange positioning bugs in some situations which I have to fix before. Currently trying to rewrite the whole calculations.

**Comment by dgwaldo** [comment]
Ok thanks! The library is pretty handy.  Only one on npm that works for our needs :)  Dragging elements around the screen is a bit of a tricky issue across browser vendors.

**Comment by spali** [comment]
closing this request. Hope #4  solves your needs.

**Pull request closed without merging**
